### ISSUE TITLE
Repo and Docker hub out of sync?

### ISSUE THREAD

**Issue by hertfelder** [hivemq/hivemq4-docker-images#20]
https://github.com/hivemq/hivemq4-docker-images/blob/aaa62bffcc42d37f5a597ca114e1c6b42dec9173/hivemq4/base-image/Dockerfile#L3

Hi guys,

on Docker hub and as announced by the newsletter, already version `4.3.3` is available. Here in the repo, it looks as if the latest version built with this Dockerfile is `4.0.0`. Are the images not built on basis of this repo? Our image is not running anymore with `4.3.3` and I suspect a breaking change in the base image. However, this is hard to check without having access to the Dockerfile.

Thanks,
Marius

**Comment by hertfelder** [comment]
@FinnHMQ Maybe you can help :)

**Comment by sbaier1** [comment]
Hey, the argument in the Dockerfile is just a default value, our CI build parameterizes this properly at build-time and builds the corresponding version, which is then pushed to DockerHub. So `hivemq/hivemq4:4.3.3` is a valid image that runs HiveMQ 4.3.3.

Can you explain what problems you are running into and what version you updated from?

**Comment by hertfelder** [comment]
Hi, thanks for the quick answer and the information. Now I understand. From `4.3.2` to `4.3.3` we have problems with two extensions (RBAC & heartbeat). Something about XML parser. My guess was missing/broken dependencies or sth like that:

```
2020-06-17 14:35:43,611 ERROR - Error in the Heartbeat Extension. Could not initialize XML parser
javax.xml.bind.JAXBException: Error while searching for service [javax.xml.bind.JAXBContextFactory]
        at javax.xml.bind.ContextFinder$1.createException(ContextFinder.java:118)
        at javax.xml.bind.ContextFinder$1.createException(ContextFinder.java:115)
        at javax.xml.bind.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:76)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:400)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
        at com.hivemq.extensions.heartbeat.configuration.ConfigurationXmlParser.<init>(ConfigurationXmlParser.java:42)
        at com.hivemq.extensions.heartbeat.configuration.ExtensionConfiguration.<init>(ExtensionConfiguration.java:32)
        at com.hivemq.extensions.heartbeat.HeartbeatMain.extensionStart(HeartbeatMain.java:57)
        at cq.b.a(Unknown Source)
        at cq.c.d(Unknown Source)
        at cY.h.c(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.ServiceConfigurationError: javax.xml.bind.JAXBContextFactory: com.sun.xml.bind.v2.JAXBContextFactory not a subtype
        at java.base/java.util.ServiceLoader.fail(Unknown Source)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
        at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
        at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
        at javax.xml.bind.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:69)
        ... 14 common frames omitted
2020-06-17 14:35:43,612 ERROR - HiveMQ Heartbeat Extension extension could not be started. An exception was thrown while starting!
java.lang.RuntimeException: Could not initialize XML parser.
        at com.hivemq.extensions.heartbeat.configuration.ConfigurationXmlParser.<init>(ConfigurationXmlParser.java:45)
        at com.hivemq.extensions.heartbeat.configuration.ExtensionConfiguration.<init>(ExtensionConfiguration.java:32)
        at com.hivemq.extensions.heartbeat.HeartbeatMain.extensionStart(HeartbeatMain.java:57)
        at cq.b.a(Unknown Source)
        at cq.c.d(Unknown Source)
        at cY.h.c(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.xml.bind.JAXBException: Error while searching for service [javax.xml.bind.JAXBContextFactory]
        at javax.xml.bind.ContextFinder$1.createException(ContextFinder.java:118)
        at javax.xml.bind.ContextFinder$1.createException(ContextFinder.java:115)
        at javax.xml.bind.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:76)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:400)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
        at com.hivemq.extensions.heartbeat.configuration.ConfigurationXmlParser.<init>(ConfigurationXmlParser.java:42)
        ... 10 common frames omitted
Caused by: java.util.ServiceConfigurationError: javax.xml.bind.JAXBContextFactory: com.sun.xml.bind.v2.JAXBContextFactory not a subtype
        at java.base/java.util.ServiceLoader.fail(Unknown Source)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
        at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
        at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
        at javax.xml.bind.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:69)
        ... 14 common frames omitted
2020-06-17 14:35:43,613 INFO  - Startup of extension with id "hivemq-heartbeat-extension" was prevented by the extension itself, reason: Heartbeat Extension cannot be started.. Extension will be disabled.
```

I can also open this on support.hivemq.com (we are an enterprise customer). Opened it here since I could link to the Dockerfile.

**Comment by sbaier1** [comment]
Your assumption is correct, a dependency upgrade in 4.3.3 could lead to problems with previous versions of the plugins. We have released updated versions of both the heartbeat & RBAC extensions that fix this problem, so updating those should fix your problem:

https://www.hivemq.com/extension/heartbeat-extension/
https://www.hivemq.com/extension/file-rbac-extension/

**Comment by hertfelder** [comment]
Perfect, thanks. That answers it, so I will close the issue here.

One last thought: Assuming semantic versioning, this breaking change was not foreseeable, since only the patch level was increased ;)
